// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ApplicationId.proto

package protocol.protocolBuf;

public final class ApplicationIdProtos {
  private ApplicationIdProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ApplicationIdOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string appIdStrPrefix = 1;
    /**
     * <code>required string appIdStrPrefix = 1;</code>
     */
    boolean hasAppIdStrPrefix();
    /**
     * <code>required string appIdStrPrefix = 1;</code>
     */
    java.lang.String getAppIdStrPrefix();
    /**
     * <code>required string appIdStrPrefix = 1;</code>
     */
    com.google.protobuf.ByteString
        getAppIdStrPrefixBytes();

    // required int32 id = 2;
    /**
     * <code>required int32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 2;</code>
     */
    int getId();

    // required int64 clusterTimestamp = 3;
    /**
     * <code>required int64 clusterTimestamp = 3;</code>
     */
    boolean hasClusterTimestamp();
    /**
     * <code>required int64 clusterTimestamp = 3;</code>
     */
    long getClusterTimestamp();
  }
  /**
   * Protobuf type {@code protocol.protocolBuf.ApplicationId}
   */
  public static final class ApplicationId extends
      com.google.protobuf.GeneratedMessage
      implements ApplicationIdOrBuilder {
    // Use ApplicationId.newBuilder() to construct.
    private ApplicationId(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ApplicationId(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ApplicationId defaultInstance;
    public static ApplicationId getDefaultInstance() {
      return defaultInstance;
    }

    public ApplicationId getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ApplicationId(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              appIdStrPrefix_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              clusterTimestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.protocolBuf.ApplicationIdProtos.internal_static_protocol_protocolBuf_ApplicationId_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.protocolBuf.ApplicationIdProtos.internal_static_protocol_protocolBuf_ApplicationId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.protocolBuf.ApplicationIdProtos.ApplicationId.class, protocol.protocolBuf.ApplicationIdProtos.ApplicationId.Builder.class);
    }

    public static com.google.protobuf.Parser<ApplicationId> PARSER =
        new com.google.protobuf.AbstractParser<ApplicationId>() {
      public ApplicationId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ApplicationId(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ApplicationId> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string appIdStrPrefix = 1;
    public static final int APPIDSTRPREFIX_FIELD_NUMBER = 1;
    private java.lang.Object appIdStrPrefix_;
    /**
     * <code>required string appIdStrPrefix = 1;</code>
     */
    public boolean hasAppIdStrPrefix() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string appIdStrPrefix = 1;</code>
     */
    public java.lang.String getAppIdStrPrefix() {
      java.lang.Object ref = appIdStrPrefix_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appIdStrPrefix_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string appIdStrPrefix = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAppIdStrPrefixBytes() {
      java.lang.Object ref = appIdStrPrefix_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appIdStrPrefix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>required int32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    // required int64 clusterTimestamp = 3;
    public static final int CLUSTERTIMESTAMP_FIELD_NUMBER = 3;
    private long clusterTimestamp_;
    /**
     * <code>required int64 clusterTimestamp = 3;</code>
     */
    public boolean hasClusterTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 clusterTimestamp = 3;</code>
     */
    public long getClusterTimestamp() {
      return clusterTimestamp_;
    }

    private void initFields() {
      appIdStrPrefix_ = "";
      id_ = 0;
      clusterTimestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAppIdStrPrefix()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClusterTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAppIdStrPrefixBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, clusterTimestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAppIdStrPrefixBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, clusterTimestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.protocolBuf.ApplicationIdProtos.ApplicationId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.protocolBuf.ApplicationIdProtos.ApplicationId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.protocolBuf.ApplicationIdProtos.ApplicationId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.protocolBuf.ApplicationIdProtos.ApplicationId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.protocolBuf.ApplicationIdProtos.ApplicationId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.protocolBuf.ApplicationIdProtos.ApplicationId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.protocolBuf.ApplicationIdProtos.ApplicationId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.protocolBuf.ApplicationIdProtos.ApplicationId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.protocolBuf.ApplicationIdProtos.ApplicationId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.protocolBuf.ApplicationIdProtos.ApplicationId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.protocolBuf.ApplicationIdProtos.ApplicationId prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.protocolBuf.ApplicationId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protocol.protocolBuf.ApplicationIdProtos.ApplicationIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.protocolBuf.ApplicationIdProtos.internal_static_protocol_protocolBuf_ApplicationId_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.protocolBuf.ApplicationIdProtos.internal_static_protocol_protocolBuf_ApplicationId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.protocolBuf.ApplicationIdProtos.ApplicationId.class, protocol.protocolBuf.ApplicationIdProtos.ApplicationId.Builder.class);
      }

      // Construct using protocol.protocolBuf.ApplicationIdProtos.ApplicationId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        appIdStrPrefix_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        clusterTimestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.protocolBuf.ApplicationIdProtos.internal_static_protocol_protocolBuf_ApplicationId_descriptor;
      }

      public protocol.protocolBuf.ApplicationIdProtos.ApplicationId getDefaultInstanceForType() {
        return protocol.protocolBuf.ApplicationIdProtos.ApplicationId.getDefaultInstance();
      }

      public protocol.protocolBuf.ApplicationIdProtos.ApplicationId build() {
        protocol.protocolBuf.ApplicationIdProtos.ApplicationId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.protocolBuf.ApplicationIdProtos.ApplicationId buildPartial() {
        protocol.protocolBuf.ApplicationIdProtos.ApplicationId result = new protocol.protocolBuf.ApplicationIdProtos.ApplicationId(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.appIdStrPrefix_ = appIdStrPrefix_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.clusterTimestamp_ = clusterTimestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.protocolBuf.ApplicationIdProtos.ApplicationId) {
          return mergeFrom((protocol.protocolBuf.ApplicationIdProtos.ApplicationId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.protocolBuf.ApplicationIdProtos.ApplicationId other) {
        if (other == protocol.protocolBuf.ApplicationIdProtos.ApplicationId.getDefaultInstance()) return this;
        if (other.hasAppIdStrPrefix()) {
          bitField0_ |= 0x00000001;
          appIdStrPrefix_ = other.appIdStrPrefix_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasClusterTimestamp()) {
          setClusterTimestamp(other.getClusterTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAppIdStrPrefix()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        if (!hasClusterTimestamp()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.protocolBuf.ApplicationIdProtos.ApplicationId parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.protocolBuf.ApplicationIdProtos.ApplicationId) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string appIdStrPrefix = 1;
      private java.lang.Object appIdStrPrefix_ = "";
      /**
       * <code>required string appIdStrPrefix = 1;</code>
       */
      public boolean hasAppIdStrPrefix() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string appIdStrPrefix = 1;</code>
       */
      public java.lang.String getAppIdStrPrefix() {
        java.lang.Object ref = appIdStrPrefix_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          appIdStrPrefix_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string appIdStrPrefix = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAppIdStrPrefixBytes() {
        java.lang.Object ref = appIdStrPrefix_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appIdStrPrefix_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string appIdStrPrefix = 1;</code>
       */
      public Builder setAppIdStrPrefix(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        appIdStrPrefix_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string appIdStrPrefix = 1;</code>
       */
      public Builder clearAppIdStrPrefix() {
        bitField0_ = (bitField0_ & ~0x00000001);
        appIdStrPrefix_ = getDefaultInstance().getAppIdStrPrefix();
        onChanged();
        return this;
      }
      /**
       * <code>required string appIdStrPrefix = 1;</code>
       */
      public Builder setAppIdStrPrefixBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        appIdStrPrefix_ = value;
        onChanged();
        return this;
      }

      // required int32 id = 2;
      private int id_ ;
      /**
       * <code>required int32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      // required int64 clusterTimestamp = 3;
      private long clusterTimestamp_ ;
      /**
       * <code>required int64 clusterTimestamp = 3;</code>
       */
      public boolean hasClusterTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 clusterTimestamp = 3;</code>
       */
      public long getClusterTimestamp() {
        return clusterTimestamp_;
      }
      /**
       * <code>required int64 clusterTimestamp = 3;</code>
       */
      public Builder setClusterTimestamp(long value) {
        bitField0_ |= 0x00000004;
        clusterTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 clusterTimestamp = 3;</code>
       */
      public Builder clearClusterTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        clusterTimestamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol.protocolBuf.ApplicationId)
    }

    static {
      defaultInstance = new ApplicationId(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocol.protocolBuf.ApplicationId)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_protocolBuf_ApplicationId_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_protocolBuf_ApplicationId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ApplicationId.proto\022\024protocol.protocol" +
      "Buf\"M\n\rApplicationId\022\026\n\016appIdStrPrefix\030\001" +
      " \002(\t\022\n\n\002id\030\002 \002(\005\022\030\n\020clusterTimestamp\030\003 \002" +
      "(\003B\025B\023ApplicationIdProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protocol_protocolBuf_ApplicationId_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protocol_protocolBuf_ApplicationId_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_protocolBuf_ApplicationId_descriptor,
              new java.lang.String[] { "AppIdStrPrefix", "Id", "ClusterTimestamp", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
