// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetNewApplicationResponse.proto

package protocol.protocolBuf;

public final class GetNewApplicationResoponseProtos {
  private GetNewApplicationResoponseProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GetNewApplicationResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .protocol.protocolBuf.ApplicationId applicationId = 1;
    /**
     * <code>required .protocol.protocolBuf.ApplicationId applicationId = 1;</code>
     */
    boolean hasApplicationId();
    /**
     * <code>required .protocol.protocolBuf.ApplicationId applicationId = 1;</code>
     */
    protocol.protocolBuf.ApplicationIdProtos.ApplicationId getApplicationId();
    /**
     * <code>required .protocol.protocolBuf.ApplicationId applicationId = 1;</code>
     */
    protocol.protocolBuf.ApplicationIdProtos.ApplicationIdOrBuilder getApplicationIdOrBuilder();

    // required .protocol.protocolBuf.Resource maximumResourceCapability = 2;
    /**
     * <code>required .protocol.protocolBuf.Resource maximumResourceCapability = 2;</code>
     */
    boolean hasMaximumResourceCapability();
    /**
     * <code>required .protocol.protocolBuf.Resource maximumResourceCapability = 2;</code>
     */
    protocol.protocolBuf.ResourceProtos.Resource getMaximumResourceCapability();
    /**
     * <code>required .protocol.protocolBuf.Resource maximumResourceCapability = 2;</code>
     */
    protocol.protocolBuf.ResourceProtos.ResourceOrBuilder getMaximumResourceCapabilityOrBuilder();
  }
  /**
   * Protobuf type {@code protocol.protocolBuf.GetNewApplicationResponse}
   */
  public static final class GetNewApplicationResponse extends
      com.google.protobuf.GeneratedMessage
      implements GetNewApplicationResponseOrBuilder {
    // Use GetNewApplicationResponse.newBuilder() to construct.
    private GetNewApplicationResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetNewApplicationResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetNewApplicationResponse defaultInstance;
    public static GetNewApplicationResponse getDefaultInstance() {
      return defaultInstance;
    }

    public GetNewApplicationResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetNewApplicationResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              protocol.protocolBuf.ApplicationIdProtos.ApplicationId.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = applicationId_.toBuilder();
              }
              applicationId_ = input.readMessage(protocol.protocolBuf.ApplicationIdProtos.ApplicationId.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(applicationId_);
                applicationId_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              protocol.protocolBuf.ResourceProtos.Resource.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = maximumResourceCapability_.toBuilder();
              }
              maximumResourceCapability_ = input.readMessage(protocol.protocolBuf.ResourceProtos.Resource.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(maximumResourceCapability_);
                maximumResourceCapability_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.protocolBuf.GetNewApplicationResoponseProtos.internal_static_protocol_protocolBuf_GetNewApplicationResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.protocolBuf.GetNewApplicationResoponseProtos.internal_static_protocol_protocolBuf_GetNewApplicationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse.class, protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<GetNewApplicationResponse> PARSER =
        new com.google.protobuf.AbstractParser<GetNewApplicationResponse>() {
      public GetNewApplicationResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetNewApplicationResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetNewApplicationResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .protocol.protocolBuf.ApplicationId applicationId = 1;
    public static final int APPLICATIONID_FIELD_NUMBER = 1;
    private protocol.protocolBuf.ApplicationIdProtos.ApplicationId applicationId_;
    /**
     * <code>required .protocol.protocolBuf.ApplicationId applicationId = 1;</code>
     */
    public boolean hasApplicationId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .protocol.protocolBuf.ApplicationId applicationId = 1;</code>
     */
    public protocol.protocolBuf.ApplicationIdProtos.ApplicationId getApplicationId() {
      return applicationId_;
    }
    /**
     * <code>required .protocol.protocolBuf.ApplicationId applicationId = 1;</code>
     */
    public protocol.protocolBuf.ApplicationIdProtos.ApplicationIdOrBuilder getApplicationIdOrBuilder() {
      return applicationId_;
    }

    // required .protocol.protocolBuf.Resource maximumResourceCapability = 2;
    public static final int MAXIMUMRESOURCECAPABILITY_FIELD_NUMBER = 2;
    private protocol.protocolBuf.ResourceProtos.Resource maximumResourceCapability_;
    /**
     * <code>required .protocol.protocolBuf.Resource maximumResourceCapability = 2;</code>
     */
    public boolean hasMaximumResourceCapability() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .protocol.protocolBuf.Resource maximumResourceCapability = 2;</code>
     */
    public protocol.protocolBuf.ResourceProtos.Resource getMaximumResourceCapability() {
      return maximumResourceCapability_;
    }
    /**
     * <code>required .protocol.protocolBuf.Resource maximumResourceCapability = 2;</code>
     */
    public protocol.protocolBuf.ResourceProtos.ResourceOrBuilder getMaximumResourceCapabilityOrBuilder() {
      return maximumResourceCapability_;
    }

    private void initFields() {
      applicationId_ = protocol.protocolBuf.ApplicationIdProtos.ApplicationId.getDefaultInstance();
      maximumResourceCapability_ = protocol.protocolBuf.ResourceProtos.Resource.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasApplicationId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMaximumResourceCapability()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getApplicationId().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getMaximumResourceCapability().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, applicationId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, maximumResourceCapability_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, applicationId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, maximumResourceCapability_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.protocolBuf.GetNewApplicationResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.protocolBuf.GetNewApplicationResoponseProtos.internal_static_protocol_protocolBuf_GetNewApplicationResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.protocolBuf.GetNewApplicationResoponseProtos.internal_static_protocol_protocolBuf_GetNewApplicationResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse.class, protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse.Builder.class);
      }

      // Construct using protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getApplicationIdFieldBuilder();
          getMaximumResourceCapabilityFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (applicationIdBuilder_ == null) {
          applicationId_ = protocol.protocolBuf.ApplicationIdProtos.ApplicationId.getDefaultInstance();
        } else {
          applicationIdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (maximumResourceCapabilityBuilder_ == null) {
          maximumResourceCapability_ = protocol.protocolBuf.ResourceProtos.Resource.getDefaultInstance();
        } else {
          maximumResourceCapabilityBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.protocolBuf.GetNewApplicationResoponseProtos.internal_static_protocol_protocolBuf_GetNewApplicationResponse_descriptor;
      }

      public protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse getDefaultInstanceForType() {
        return protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse.getDefaultInstance();
      }

      public protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse build() {
        protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse buildPartial() {
        protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse result = new protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (applicationIdBuilder_ == null) {
          result.applicationId_ = applicationId_;
        } else {
          result.applicationId_ = applicationIdBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (maximumResourceCapabilityBuilder_ == null) {
          result.maximumResourceCapability_ = maximumResourceCapability_;
        } else {
          result.maximumResourceCapability_ = maximumResourceCapabilityBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse) {
          return mergeFrom((protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse other) {
        if (other == protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse.getDefaultInstance()) return this;
        if (other.hasApplicationId()) {
          mergeApplicationId(other.getApplicationId());
        }
        if (other.hasMaximumResourceCapability()) {
          mergeMaximumResourceCapability(other.getMaximumResourceCapability());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasApplicationId()) {
          
          return false;
        }
        if (!hasMaximumResourceCapability()) {
          
          return false;
        }
        if (!getApplicationId().isInitialized()) {
          
          return false;
        }
        if (!getMaximumResourceCapability().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.protocolBuf.GetNewApplicationResoponseProtos.GetNewApplicationResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .protocol.protocolBuf.ApplicationId applicationId = 1;
      private protocol.protocolBuf.ApplicationIdProtos.ApplicationId applicationId_ = protocol.protocolBuf.ApplicationIdProtos.ApplicationId.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          protocol.protocolBuf.ApplicationIdProtos.ApplicationId, protocol.protocolBuf.ApplicationIdProtos.ApplicationId.Builder, protocol.protocolBuf.ApplicationIdProtos.ApplicationIdOrBuilder> applicationIdBuilder_;
      /**
       * <code>required .protocol.protocolBuf.ApplicationId applicationId = 1;</code>
       */
      public boolean hasApplicationId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .protocol.protocolBuf.ApplicationId applicationId = 1;</code>
       */
      public protocol.protocolBuf.ApplicationIdProtos.ApplicationId getApplicationId() {
        if (applicationIdBuilder_ == null) {
          return applicationId_;
        } else {
          return applicationIdBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protocol.protocolBuf.ApplicationId applicationId = 1;</code>
       */
      public Builder setApplicationId(protocol.protocolBuf.ApplicationIdProtos.ApplicationId value) {
        if (applicationIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          applicationId_ = value;
          onChanged();
        } else {
          applicationIdBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol.protocolBuf.ApplicationId applicationId = 1;</code>
       */
      public Builder setApplicationId(
          protocol.protocolBuf.ApplicationIdProtos.ApplicationId.Builder builderForValue) {
        if (applicationIdBuilder_ == null) {
          applicationId_ = builderForValue.build();
          onChanged();
        } else {
          applicationIdBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol.protocolBuf.ApplicationId applicationId = 1;</code>
       */
      public Builder mergeApplicationId(protocol.protocolBuf.ApplicationIdProtos.ApplicationId value) {
        if (applicationIdBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              applicationId_ != protocol.protocolBuf.ApplicationIdProtos.ApplicationId.getDefaultInstance()) {
            applicationId_ =
              protocol.protocolBuf.ApplicationIdProtos.ApplicationId.newBuilder(applicationId_).mergeFrom(value).buildPartial();
          } else {
            applicationId_ = value;
          }
          onChanged();
        } else {
          applicationIdBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol.protocolBuf.ApplicationId applicationId = 1;</code>
       */
      public Builder clearApplicationId() {
        if (applicationIdBuilder_ == null) {
          applicationId_ = protocol.protocolBuf.ApplicationIdProtos.ApplicationId.getDefaultInstance();
          onChanged();
        } else {
          applicationIdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .protocol.protocolBuf.ApplicationId applicationId = 1;</code>
       */
      public protocol.protocolBuf.ApplicationIdProtos.ApplicationId.Builder getApplicationIdBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getApplicationIdFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protocol.protocolBuf.ApplicationId applicationId = 1;</code>
       */
      public protocol.protocolBuf.ApplicationIdProtos.ApplicationIdOrBuilder getApplicationIdOrBuilder() {
        if (applicationIdBuilder_ != null) {
          return applicationIdBuilder_.getMessageOrBuilder();
        } else {
          return applicationId_;
        }
      }
      /**
       * <code>required .protocol.protocolBuf.ApplicationId applicationId = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protocol.protocolBuf.ApplicationIdProtos.ApplicationId, protocol.protocolBuf.ApplicationIdProtos.ApplicationId.Builder, protocol.protocolBuf.ApplicationIdProtos.ApplicationIdOrBuilder> 
          getApplicationIdFieldBuilder() {
        if (applicationIdBuilder_ == null) {
          applicationIdBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protocol.protocolBuf.ApplicationIdProtos.ApplicationId, protocol.protocolBuf.ApplicationIdProtos.ApplicationId.Builder, protocol.protocolBuf.ApplicationIdProtos.ApplicationIdOrBuilder>(
                  applicationId_,
                  getParentForChildren(),
                  isClean());
          applicationId_ = null;
        }
        return applicationIdBuilder_;
      }

      // required .protocol.protocolBuf.Resource maximumResourceCapability = 2;
      private protocol.protocolBuf.ResourceProtos.Resource maximumResourceCapability_ = protocol.protocolBuf.ResourceProtos.Resource.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          protocol.protocolBuf.ResourceProtos.Resource, protocol.protocolBuf.ResourceProtos.Resource.Builder, protocol.protocolBuf.ResourceProtos.ResourceOrBuilder> maximumResourceCapabilityBuilder_;
      /**
       * <code>required .protocol.protocolBuf.Resource maximumResourceCapability = 2;</code>
       */
      public boolean hasMaximumResourceCapability() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .protocol.protocolBuf.Resource maximumResourceCapability = 2;</code>
       */
      public protocol.protocolBuf.ResourceProtos.Resource getMaximumResourceCapability() {
        if (maximumResourceCapabilityBuilder_ == null) {
          return maximumResourceCapability_;
        } else {
          return maximumResourceCapabilityBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protocol.protocolBuf.Resource maximumResourceCapability = 2;</code>
       */
      public Builder setMaximumResourceCapability(protocol.protocolBuf.ResourceProtos.Resource value) {
        if (maximumResourceCapabilityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          maximumResourceCapability_ = value;
          onChanged();
        } else {
          maximumResourceCapabilityBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protocol.protocolBuf.Resource maximumResourceCapability = 2;</code>
       */
      public Builder setMaximumResourceCapability(
          protocol.protocolBuf.ResourceProtos.Resource.Builder builderForValue) {
        if (maximumResourceCapabilityBuilder_ == null) {
          maximumResourceCapability_ = builderForValue.build();
          onChanged();
        } else {
          maximumResourceCapabilityBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protocol.protocolBuf.Resource maximumResourceCapability = 2;</code>
       */
      public Builder mergeMaximumResourceCapability(protocol.protocolBuf.ResourceProtos.Resource value) {
        if (maximumResourceCapabilityBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              maximumResourceCapability_ != protocol.protocolBuf.ResourceProtos.Resource.getDefaultInstance()) {
            maximumResourceCapability_ =
              protocol.protocolBuf.ResourceProtos.Resource.newBuilder(maximumResourceCapability_).mergeFrom(value).buildPartial();
          } else {
            maximumResourceCapability_ = value;
          }
          onChanged();
        } else {
          maximumResourceCapabilityBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protocol.protocolBuf.Resource maximumResourceCapability = 2;</code>
       */
      public Builder clearMaximumResourceCapability() {
        if (maximumResourceCapabilityBuilder_ == null) {
          maximumResourceCapability_ = protocol.protocolBuf.ResourceProtos.Resource.getDefaultInstance();
          onChanged();
        } else {
          maximumResourceCapabilityBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .protocol.protocolBuf.Resource maximumResourceCapability = 2;</code>
       */
      public protocol.protocolBuf.ResourceProtos.Resource.Builder getMaximumResourceCapabilityBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getMaximumResourceCapabilityFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protocol.protocolBuf.Resource maximumResourceCapability = 2;</code>
       */
      public protocol.protocolBuf.ResourceProtos.ResourceOrBuilder getMaximumResourceCapabilityOrBuilder() {
        if (maximumResourceCapabilityBuilder_ != null) {
          return maximumResourceCapabilityBuilder_.getMessageOrBuilder();
        } else {
          return maximumResourceCapability_;
        }
      }
      /**
       * <code>required .protocol.protocolBuf.Resource maximumResourceCapability = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protocol.protocolBuf.ResourceProtos.Resource, protocol.protocolBuf.ResourceProtos.Resource.Builder, protocol.protocolBuf.ResourceProtos.ResourceOrBuilder> 
          getMaximumResourceCapabilityFieldBuilder() {
        if (maximumResourceCapabilityBuilder_ == null) {
          maximumResourceCapabilityBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protocol.protocolBuf.ResourceProtos.Resource, protocol.protocolBuf.ResourceProtos.Resource.Builder, protocol.protocolBuf.ResourceProtos.ResourceOrBuilder>(
                  maximumResourceCapability_,
                  getParentForChildren(),
                  isClean());
          maximumResourceCapability_ = null;
        }
        return maximumResourceCapabilityBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protocol.protocolBuf.GetNewApplicationResponse)
    }

    static {
      defaultInstance = new GetNewApplicationResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocol.protocolBuf.GetNewApplicationResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_protocolBuf_GetNewApplicationResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_protocolBuf_GetNewApplicationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037GetNewApplicationResponse.proto\022\024proto" +
      "col.protocolBuf\032\023ApplicationId.proto\032\016Re" +
      "source.proto\"\232\001\n\031GetNewApplicationRespon" +
      "se\022:\n\rapplicationId\030\001 \002(\0132#.protocol.pro" +
      "tocolBuf.ApplicationId\022A\n\031maximumResourc" +
      "eCapability\030\002 \002(\0132\036.protocol.protocolBuf" +
      ".ResourceB\"B GetNewApplicationResoponseP" +
      "rotos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protocol_protocolBuf_GetNewApplicationResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protocol_protocolBuf_GetNewApplicationResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_protocolBuf_GetNewApplicationResponse_descriptor,
              new java.lang.String[] { "ApplicationId", "MaximumResourceCapability", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protocol.protocolBuf.ApplicationIdProtos.getDescriptor(),
          protocol.protocolBuf.ResourceProtos.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
