// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Resource.proto

package protocol.protocolBuf;

public final class ResourceProtos {
  private ResourceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ResourceOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 memory = 1;
    /**
     * <code>required int32 memory = 1;</code>
     */
    boolean hasMemory();
    /**
     * <code>required int32 memory = 1;</code>
     */
    int getMemory();

    // required int32 vCores = 2;
    /**
     * <code>required int32 vCores = 2;</code>
     */
    boolean hasVCores();
    /**
     * <code>required int32 vCores = 2;</code>
     */
    int getVCores();
  }
  /**
   * Protobuf type {@code protocol.protocolBuf.Resource}
   */
  public static final class Resource extends
      com.google.protobuf.GeneratedMessage
      implements ResourceOrBuilder {
    // Use Resource.newBuilder() to construct.
    private Resource(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Resource(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Resource defaultInstance;
    public static Resource getDefaultInstance() {
      return defaultInstance;
    }

    public Resource getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Resource(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              memory_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              vCores_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.protocolBuf.ResourceProtos.internal_static_protocol_protocolBuf_Resource_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.protocolBuf.ResourceProtos.internal_static_protocol_protocolBuf_Resource_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.protocolBuf.ResourceProtos.Resource.class, protocol.protocolBuf.ResourceProtos.Resource.Builder.class);
    }

    public static com.google.protobuf.Parser<Resource> PARSER =
        new com.google.protobuf.AbstractParser<Resource>() {
      public Resource parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Resource(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Resource> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 memory = 1;
    public static final int MEMORY_FIELD_NUMBER = 1;
    private int memory_;
    /**
     * <code>required int32 memory = 1;</code>
     */
    public boolean hasMemory() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 memory = 1;</code>
     */
    public int getMemory() {
      return memory_;
    }

    // required int32 vCores = 2;
    public static final int VCORES_FIELD_NUMBER = 2;
    private int vCores_;
    /**
     * <code>required int32 vCores = 2;</code>
     */
    public boolean hasVCores() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 vCores = 2;</code>
     */
    public int getVCores() {
      return vCores_;
    }

    private void initFields() {
      memory_ = 0;
      vCores_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMemory()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVCores()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, memory_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, vCores_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, memory_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, vCores_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.protocolBuf.ResourceProtos.Resource parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.protocolBuf.ResourceProtos.Resource parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.protocolBuf.ResourceProtos.Resource parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.protocolBuf.ResourceProtos.Resource parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.protocolBuf.ResourceProtos.Resource parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.protocolBuf.ResourceProtos.Resource parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.protocolBuf.ResourceProtos.Resource parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.protocolBuf.ResourceProtos.Resource parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.protocolBuf.ResourceProtos.Resource parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.protocolBuf.ResourceProtos.Resource parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.protocolBuf.ResourceProtos.Resource prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.protocolBuf.Resource}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protocol.protocolBuf.ResourceProtos.ResourceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.protocolBuf.ResourceProtos.internal_static_protocol_protocolBuf_Resource_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.protocolBuf.ResourceProtos.internal_static_protocol_protocolBuf_Resource_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.protocolBuf.ResourceProtos.Resource.class, protocol.protocolBuf.ResourceProtos.Resource.Builder.class);
      }

      // Construct using protocol.protocolBuf.ResourceProtos.Resource.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        memory_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        vCores_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.protocolBuf.ResourceProtos.internal_static_protocol_protocolBuf_Resource_descriptor;
      }

      public protocol.protocolBuf.ResourceProtos.Resource getDefaultInstanceForType() {
        return protocol.protocolBuf.ResourceProtos.Resource.getDefaultInstance();
      }

      public protocol.protocolBuf.ResourceProtos.Resource build() {
        protocol.protocolBuf.ResourceProtos.Resource result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.protocolBuf.ResourceProtos.Resource buildPartial() {
        protocol.protocolBuf.ResourceProtos.Resource result = new protocol.protocolBuf.ResourceProtos.Resource(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.memory_ = memory_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.vCores_ = vCores_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.protocolBuf.ResourceProtos.Resource) {
          return mergeFrom((protocol.protocolBuf.ResourceProtos.Resource)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.protocolBuf.ResourceProtos.Resource other) {
        if (other == protocol.protocolBuf.ResourceProtos.Resource.getDefaultInstance()) return this;
        if (other.hasMemory()) {
          setMemory(other.getMemory());
        }
        if (other.hasVCores()) {
          setVCores(other.getVCores());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMemory()) {
          
          return false;
        }
        if (!hasVCores()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.protocolBuf.ResourceProtos.Resource parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.protocolBuf.ResourceProtos.Resource) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 memory = 1;
      private int memory_ ;
      /**
       * <code>required int32 memory = 1;</code>
       */
      public boolean hasMemory() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 memory = 1;</code>
       */
      public int getMemory() {
        return memory_;
      }
      /**
       * <code>required int32 memory = 1;</code>
       */
      public Builder setMemory(int value) {
        bitField0_ |= 0x00000001;
        memory_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 memory = 1;</code>
       */
      public Builder clearMemory() {
        bitField0_ = (bitField0_ & ~0x00000001);
        memory_ = 0;
        onChanged();
        return this;
      }

      // required int32 vCores = 2;
      private int vCores_ ;
      /**
       * <code>required int32 vCores = 2;</code>
       */
      public boolean hasVCores() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 vCores = 2;</code>
       */
      public int getVCores() {
        return vCores_;
      }
      /**
       * <code>required int32 vCores = 2;</code>
       */
      public Builder setVCores(int value) {
        bitField0_ |= 0x00000002;
        vCores_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 vCores = 2;</code>
       */
      public Builder clearVCores() {
        bitField0_ = (bitField0_ & ~0x00000002);
        vCores_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol.protocolBuf.Resource)
    }

    static {
      defaultInstance = new Resource(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocol.protocolBuf.Resource)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_protocolBuf_Resource_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_protocolBuf_Resource_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Resource.proto\022\024protocol.protocolBuf\"*" +
      "\n\010Resource\022\016\n\006memory\030\001 \002(\005\022\016\n\006vCores\030\002 \002" +
      "(\005B\020B\016ResourceProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protocol_protocolBuf_Resource_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protocol_protocolBuf_Resource_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_protocolBuf_Resource_descriptor,
              new java.lang.String[] { "Memory", "VCores", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
